#############################################################################
# Makefile for building: arhud
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  arhud.pro
# Template: app
# Command: /usr/lib/i386-linux-gnu/qt5/bin/qmake -o Makefile arhud.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_WEBKITWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_WEBKIT_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../Libs -I../Hdr -I. -I../qjson-master/build -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtOpenGL -isystem /usr/include/i386-linux-gnu/qt5/QtMultimediaWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtWebKitWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtWebKit -isystem /usr/include/i386-linux-gnu/qt5/QtMultimedia -isystem /usr/include/i386-linux-gnu/qt5/QtGui -isystem /usr/include/i386-linux-gnu/qt5/QtXml -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/i386-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = arhud1.0.0
DISTDIR = /home/cll/V2N2V/ARHUD_18-Feb/.tmp/arhud1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib/i386-linux-gnu
LIBS          = $(SUBLIBS) /home/cll/V2N2V/ARHUD_18-Feb/../Libs/libMediaFramework.a /home/cll/V2N2V/ARHUD_18-Feb/../Libs/libPlatform.a /home/cll/V2N2V/ARHUD_18-Feb/../Libs/libUtils.a /home/cll/V2N2V/ARHUD_18-Feb/../Libs/lib_Color_conversion_YUYVtoYUV420_Linux_x86_32bit_v1_0.a /home/cll/V2N2V/ARHUD_18-Feb/../Libs/lib_H264_CBP_Decoder_x86_Linux_32_V1_2.a /home/cll/V2N2V/ARHUD_18-Feb/../Libs/lib_H264CBP_Encoder_linux_32bit_v1_4.a /home/cll/V2N2V/ARHUD_18-Feb/../Libs/lib_Scaling_x86.a -lSDL -lSDLmain /home/cll/V2N2V/ARHUD_18-Feb/./libv4l2wrapper.a -L/home/cll/V2N2V/ARHUD_18-Feb/../qjson-master/build/lib/ -lqjson-qt5 -lQt5OpenGL -lQt5MultimediaWidgets -lQt5WebKitWidgets -lQt5Widgets -lQt5WebKit -lQt5Multimedia -lQt5Gui -lQt5Xml -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		arhud.cpp \
		v2n.cpp \
		v2n2v.cpp \
		v2v.cpp \
		settings.cpp \
		camerapreviewwindow.cpp \
		geocode_data_manager.cpp \
		winclassapp.cpp qrc_resources.cpp \
		moc_arhud.cpp \
		moc_v2n.cpp \
		moc_v2n2v.cpp \
		moc_v2v.cpp \
		moc_settings.cpp \
		moc_camerapreviewwindow.cpp \
		moc_geocode_data_manager.cpp
OBJECTS       = main.o \
		arhud.o \
		v2n.o \
		v2n2v.o \
		v2v.o \
		settings.o \
		camerapreviewwindow.o \
		geocode_data_manager.o \
		winclassapp.o \
		qrc_resources.o \
		moc_arhud.o \
		moc_v2n.o \
		moc_v2n2v.o \
		moc_v2v.o \
		moc_settings.o \
		moc_camerapreviewwindow.o \
		moc_geocode_data_manager.o
DIST          = google_maps.html \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcollision.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3drenderer.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_contacts.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_organizer.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_versit.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_versitorganizer.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf \
		arhud.pro streamer_receiver_library.h \
		arhud.h \
		v2n.h \
		v2n2v.h \
		v2v.h \
		settings.h \
		camerapreviewwindow.h \
		libcam.h \
		x264.h \
		V4l2Access.h \
		V4l2Capture.h \
		V4l2Device.h \
		V4l2MmapDevice.h \
		V4l2ReadWriteDevice.h \
		V4l2Output.h \
		geocode_data_manager.h \
		../Hdr/winclassapp.h \
		../Hdr/Nw_Utility.h \
		../Hdr/MMFrStaticMetaDataAPI.h \
		../Hdr/MMFrUtil.h \
		../Hdr/MMFrRecorderAPI.h \
		../Hdr/MMFrPlayerAPI.h \
		../Hdr/MMFrNetworkFileTransfer.h \
		../Hdr/MMFrMetaData.h \
		../Hdr/MMFrIO.h \
		../Hdr/MMFrImageViewerAPI.h \
		../Hdr/MMFrDataTypes.h \
		../Hdr/MediaServerAPI.h \
		../Hdr/MediaSDPParser.h \
		../Hdr/MediaManagerAPI.h \
		../Hdr/MediaConference.h main.cpp \
		arhud.cpp \
		v2n.cpp \
		v2n2v.cpp \
		v2v.cpp \
		settings.cpp \
		camerapreviewwindow.cpp \
		geocode_data_manager.cpp \
		winclassapp.cpp
QMAKE_TARGET  = arhud
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = arhud


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): /home/cll/V2N2V/ARHUD_18-Feb/../Libs/libMediaFramework.a /home/cll/V2N2V/ARHUD_18-Feb/../Libs/libPlatform.a /home/cll/V2N2V/ARHUD_18-Feb/../Libs/libUtils.a /home/cll/V2N2V/ARHUD_18-Feb/../Libs/lib_Color_conversion_YUYVtoYUV420_Linux_x86_32bit_v1_0.a /home/cll/V2N2V/ARHUD_18-Feb/../Libs/lib_H264_CBP_Decoder_x86_Linux_32_V1_2.a /home/cll/V2N2V/ARHUD_18-Feb/../Libs/lib_H264CBP_Encoder_linux_32bit_v1_4.a /home/cll/V2N2V/ARHUD_18-Feb/../Libs/libMediaFramework.a /home/cll/V2N2V/ARHUD_18-Feb/../Libs/libPlatform.a /home/cll/V2N2V/ARHUD_18-Feb/../Libs/lib_Scaling_x86.a /home/cll/V2N2V/ARHUD_18-Feb/../Libs/libUtils.a /home/cll/V2N2V/ARHUD_18-Feb/./libv4l2wrapper.a ui_arhud.h ui_v2n.h ui_v2n2v.h ui_v2v.h ui_settings.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: arhud.pro /usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcollision.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3drenderer.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_contacts.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_organizer.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_versit.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_versitorganizer.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf \
		arhud.pro \
		resources.qrc \
		/usr/lib/i386-linux-gnu/libQt5OpenGL.prl \
		/usr/lib/i386-linux-gnu/libQt5MultimediaWidgets.prl \
		/usr/lib/i386-linux-gnu/libQt5WebKitWidgets.prl \
		/usr/lib/i386-linux-gnu/libQt5Widgets.prl \
		/usr/lib/i386-linux-gnu/libQt5WebKit.prl \
		/usr/lib/i386-linux-gnu/libQt5Multimedia.prl \
		/usr/lib/i386-linux-gnu/libQt5Gui.prl \
		/usr/lib/i386-linux-gnu/libQt5Xml.prl \
		/usr/lib/i386-linux-gnu/libQt5Network.prl \
		/usr/lib/i386-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile arhud.pro
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcollision.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrenderer.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_3drenderer.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_contacts.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_organizer.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_versit.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_versitorganizer.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf:
arhud.pro:
resources.qrc:
/usr/lib/i386-linux-gnu/libQt5OpenGL.prl:
/usr/lib/i386-linux-gnu/libQt5MultimediaWidgets.prl:
/usr/lib/i386-linux-gnu/libQt5WebKitWidgets.prl:
/usr/lib/i386-linux-gnu/libQt5Widgets.prl:
/usr/lib/i386-linux-gnu/libQt5WebKit.prl:
/usr/lib/i386-linux-gnu/libQt5Multimedia.prl:
/usr/lib/i386-linux-gnu/libQt5Gui.prl:
/usr/lib/i386-linux-gnu/libQt5Xml.prl:
/usr/lib/i386-linux-gnu/libQt5Network.prl:
/usr/lib/i386-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile arhud.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents streamer_receiver_library.h arhud.h v2n.h v2n2v.h v2v.h settings.h camerapreviewwindow.h libcam.h x264.h V4l2Access.h V4l2Capture.h V4l2Device.h V4l2MmapDevice.h V4l2ReadWriteDevice.h V4l2Output.h geocode_data_manager.h ../Hdr/winclassapp.h ../Hdr/Nw_Utility.h ../Hdr/MMFrStaticMetaDataAPI.h ../Hdr/MMFrUtil.h ../Hdr/MMFrRecorderAPI.h ../Hdr/MMFrPlayerAPI.h ../Hdr/MMFrNetworkFileTransfer.h ../Hdr/MMFrMetaData.h ../Hdr/MMFrIO.h ../Hdr/MMFrImageViewerAPI.h ../Hdr/MMFrDataTypes.h ../Hdr/MediaServerAPI.h ../Hdr/MediaSDPParser.h ../Hdr/MediaManagerAPI.h ../Hdr/MediaConference.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp arhud.cpp v2n.cpp v2n2v.cpp v2v.cpp settings.cpp camerapreviewwindow.cpp geocode_data_manager.cpp winclassapp.cpp $(DISTDIR)/
	$(COPY_FILE) --parents arhud.ui v2n.ui v2n2v.ui v2v.ui settings.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		google_maps.html \
		images/buzzer_x.ogg \
		images/background.png \
		images/return.png \
		images/black.jpg \
		images/backbutton1.png \
		images/backbutton2.png \
		images/backbutton3.png \
		images/backbutton4.png \
		images/buzzer_x.wav \
		images/settings_toolbar_back.png \
		images/Greenlight.png \
		images/menu1.png \
		images/exit1.ico \
		images/Button_APPLY.png \
		images/background3.jpg \
		images/ashcolor.png \
		images/background2.png \
		images/menu.png \
		images/white.png \
		images/Button_V2N2V.png \
		images/Button_V1Position.png \
		images/Button_V2Position.png \
		images/Button_V2N.png \
		images/toolbar_background.png \
		images/settings_toolbar_background.png \
		images/Redlight.png \
		images/Button_V2V.png
	/usr/lib/i386-linux-gnu/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_arhud.cpp moc_v2n.cpp moc_v2n2v.cpp moc_v2v.cpp moc_settings.cpp moc_camerapreviewwindow.cpp moc_geocode_data_manager.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_arhud.cpp moc_v2n.cpp moc_v2n2v.cpp moc_v2v.cpp moc_settings.cpp moc_camerapreviewwindow.cpp moc_geocode_data_manager.cpp
moc_arhud.cpp: v2n.h \
		camerapreviewwindow.h \
		streamer_receiver_library.h \
		x264.h \
		V4l2Capture.h \
		V4l2Access.h \
		V4l2Device.h \
		v2v.h \
		v2n2v.h \
		geocode_data_manager.h \
		settings.h \
		arhud.h
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cll/V2N2V/ARHUD_18-Feb -I/home/cll/V2N2V/Libs -I/home/cll/V2N2V/Hdr -I/home/cll/V2N2V/ARHUD_18-Feb -I/home/cll/V2N2V/qjson-master/build -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtOpenGL -I/usr/include/i386-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/i386-linux-gnu/qt5/QtWebKitWidgets -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtWebKit -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtXml -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/i386-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/i686-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/5/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include arhud.h -o moc_arhud.cpp

moc_v2n.cpp: camerapreviewwindow.h \
		streamer_receiver_library.h \
		x264.h \
		V4l2Capture.h \
		V4l2Access.h \
		V4l2Device.h \
		v2n.h
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cll/V2N2V/ARHUD_18-Feb -I/home/cll/V2N2V/Libs -I/home/cll/V2N2V/Hdr -I/home/cll/V2N2V/ARHUD_18-Feb -I/home/cll/V2N2V/qjson-master/build -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtOpenGL -I/usr/include/i386-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/i386-linux-gnu/qt5/QtWebKitWidgets -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtWebKit -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtXml -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/i386-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/i686-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/5/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include v2n.h -o moc_v2n.cpp

moc_v2n2v.cpp: geocode_data_manager.h \
		v2v.h \
		camerapreviewwindow.h \
		v2n.h \
		streamer_receiver_library.h \
		x264.h \
		V4l2Capture.h \
		V4l2Access.h \
		V4l2Device.h \
		v2n2v.h
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cll/V2N2V/ARHUD_18-Feb -I/home/cll/V2N2V/Libs -I/home/cll/V2N2V/Hdr -I/home/cll/V2N2V/ARHUD_18-Feb -I/home/cll/V2N2V/qjson-master/build -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtOpenGL -I/usr/include/i386-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/i386-linux-gnu/qt5/QtWebKitWidgets -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtWebKit -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtXml -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/i386-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/i686-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/5/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include v2n2v.h -o moc_v2n2v.cpp

moc_v2v.cpp: camerapreviewwindow.h \
		v2n.h \
		streamer_receiver_library.h \
		x264.h \
		V4l2Capture.h \
		V4l2Access.h \
		V4l2Device.h \
		v2v.h
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cll/V2N2V/ARHUD_18-Feb -I/home/cll/V2N2V/Libs -I/home/cll/V2N2V/Hdr -I/home/cll/V2N2V/ARHUD_18-Feb -I/home/cll/V2N2V/qjson-master/build -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtOpenGL -I/usr/include/i386-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/i386-linux-gnu/qt5/QtWebKitWidgets -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtWebKit -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtXml -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/i386-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/i686-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/5/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include v2v.h -o moc_v2v.cpp

moc_settings.cpp: settings.h
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cll/V2N2V/ARHUD_18-Feb -I/home/cll/V2N2V/Libs -I/home/cll/V2N2V/Hdr -I/home/cll/V2N2V/ARHUD_18-Feb -I/home/cll/V2N2V/qjson-master/build -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtOpenGL -I/usr/include/i386-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/i386-linux-gnu/qt5/QtWebKitWidgets -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtWebKit -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtXml -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/i386-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/i686-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/5/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include settings.h -o moc_settings.cpp

moc_camerapreviewwindow.cpp: camerapreviewwindow.h
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cll/V2N2V/ARHUD_18-Feb -I/home/cll/V2N2V/Libs -I/home/cll/V2N2V/Hdr -I/home/cll/V2N2V/ARHUD_18-Feb -I/home/cll/V2N2V/qjson-master/build -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtOpenGL -I/usr/include/i386-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/i386-linux-gnu/qt5/QtWebKitWidgets -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtWebKit -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtXml -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/i386-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/i686-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/5/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include camerapreviewwindow.h -o moc_camerapreviewwindow.cpp

moc_geocode_data_manager.cpp: geocode_data_manager.h
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cll/V2N2V/ARHUD_18-Feb -I/home/cll/V2N2V/Libs -I/home/cll/V2N2V/Hdr -I/home/cll/V2N2V/ARHUD_18-Feb -I/home/cll/V2N2V/qjson-master/build -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtOpenGL -I/usr/include/i386-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/i386-linux-gnu/qt5/QtWebKitWidgets -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtWebKit -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtXml -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/i386-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/i686-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/5/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include geocode_data_manager.h -o moc_geocode_data_manager.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_arhud.h ui_v2n.h ui_v2n2v.h ui_v2v.h ui_settings.h
compiler_uic_clean:
	-$(DEL_FILE) ui_arhud.h ui_v2n.h ui_v2n2v.h ui_v2v.h ui_settings.h
ui_arhud.h: arhud.ui
	/usr/lib/i386-linux-gnu/qt5/bin/uic arhud.ui -o ui_arhud.h

ui_v2n.h: v2n.ui
	/usr/lib/i386-linux-gnu/qt5/bin/uic v2n.ui -o ui_v2n.h

ui_v2n2v.h: v2n2v.ui \
		/usr/include/i386-linux-gnu/qt5/QtWebKitWidgets/QWebView
	/usr/lib/i386-linux-gnu/qt5/bin/uic v2n2v.ui -o ui_v2n2v.h

ui_v2v.h: v2v.ui
	/usr/lib/i386-linux-gnu/qt5/bin/uic v2v.ui -o ui_v2v.h

ui_settings.h: settings.ui
	/usr/lib/i386-linux-gnu/qt5/bin/uic settings.ui -o ui_settings.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp arhud.h \
		v2n.h \
		camerapreviewwindow.h \
		streamer_receiver_library.h \
		x264.h \
		V4l2Capture.h \
		V4l2Access.h \
		V4l2Device.h \
		v2v.h \
		v2n2v.h \
		geocode_data_manager.h \
		settings.h \
		../Hdr/MediaManagerAPI.h \
		../Hdr/MMFrIO.h \
		../Hdr/MMFrDataTypes.h \
		../Hdr/MMFrUtil.h \
		../Hdr/Nw_Utility.h \
		../Hdr/winclassapp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

arhud.o: arhud.cpp arhud.h \
		v2n.h \
		camerapreviewwindow.h \
		streamer_receiver_library.h \
		x264.h \
		V4l2Capture.h \
		V4l2Access.h \
		V4l2Device.h \
		v2v.h \
		v2n2v.h \
		geocode_data_manager.h \
		settings.h \
		ui_arhud.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o arhud.o arhud.cpp

v2n.o: v2n.cpp v2n.h \
		camerapreviewwindow.h \
		streamer_receiver_library.h \
		x264.h \
		V4l2Capture.h \
		V4l2Access.h \
		V4l2Device.h \
		ui_v2n.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o v2n.o v2n.cpp

v2n2v.o: v2n2v.cpp v2n2v.h \
		geocode_data_manager.h \
		v2v.h \
		camerapreviewwindow.h \
		v2n.h \
		streamer_receiver_library.h \
		x264.h \
		V4l2Capture.h \
		V4l2Access.h \
		V4l2Device.h \
		ui_v2n2v.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o v2n2v.o v2n2v.cpp

v2v.o: v2v.cpp v2v.h \
		camerapreviewwindow.h \
		v2n.h \
		streamer_receiver_library.h \
		x264.h \
		V4l2Capture.h \
		V4l2Access.h \
		V4l2Device.h \
		ui_v2v.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o v2v.o v2v.cpp

settings.o: settings.cpp settings.h \
		ui_settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

camerapreviewwindow.o: camerapreviewwindow.cpp camerapreviewwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camerapreviewwindow.o camerapreviewwindow.cpp

geocode_data_manager.o: geocode_data_manager.cpp geocode_data_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o geocode_data_manager.o geocode_data_manager.cpp

winclassapp.o: winclassapp.cpp ../Hdr/winclassapp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o winclassapp.o winclassapp.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_arhud.o: moc_arhud.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_arhud.o moc_arhud.cpp

moc_v2n.o: moc_v2n.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_v2n.o moc_v2n.cpp

moc_v2n2v.o: moc_v2n2v.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_v2n2v.o moc_v2n2v.cpp

moc_v2v.o: moc_v2v.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_v2v.o moc_v2v.cpp

moc_settings.o: moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settings.o moc_settings.cpp

moc_camerapreviewwindow.o: moc_camerapreviewwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_camerapreviewwindow.o moc_camerapreviewwindow.cpp

moc_geocode_data_manager.o: moc_geocode_data_manager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_geocode_data_manager.o moc_geocode_data_manager.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/arhud/bin || mkdir -p $(INSTALL_ROOT)/opt/arhud/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/arhud/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/arhud/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/arhud/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/arhud/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

